const Axios = require('axios');
const schedule = require('node-schedule');
// require("dotenv").config();


module.exports = {

  getFriendBoard: (req, res) => {
    //console.log('review req', req.body)
    var dummyData = [{"name":"Cosetta","gain":-33},
    {"name":"Ezequiel","gain":39},
    {"name":"Ase","gain":-9},
    {"name":"Dannye","gain":40},
    {"name":"Desiri","gain":1},
    {"name":"Roderigo","gain":-38},
    {"name":"Rafaello","gain":-22},
    {"name":"Ab","gain":-11},
    {"name":"Daryle","gain":-18},
    {"name":"Constantino","gain":-4},
    {"name":"Gracia","gain":-3},
    {"name":"Jacinthe","gain":6},
    {"name":"Katleen","gain":-37},
    {"name":"Skell","gain":33},
    {"name":"Quintina","gain":-36},
    {"name":"Davon","gain":-26},
    {"name":"Mabel","gain":-28},
    {"name":"Rubi","gain":-48},
    {"name":"Zackariah","gain":34},
    {"name":"Tammy","gain":37},
    {"name":"Idaline","gain":-25},
    {"name":"Evyn","gain":5},
    {"name":"Eberhard","gain":1},
    {"name":"Zacharie","gain":11},
    {"name":"Ashlee","gain":-45},
    {"name":"Robina","gain":7},
    {"name":"Hyman","gain":39},
    {"name":"Crichton","gain":5},
    {"name":"Gerald","gain":-44},
    {"name":"Darren","gain":-13},
    {"name":"Sanderson","gain":46},
    {"name":"Wilhelmine","gain":-28},
    {"name":"Jackson","gain":-1},
    {"name":"Ingunna","gain":-26},
    {"name":"Scarlet","gain":-25},
    {"name":"Kellen","gain":-39},
    {"name":"Malena","gain":-25},
    {"name":"Aloysia","gain":21},
    {"name":"Phylis","gain":-1},
    {"name":"Jammie","gain":-1},
    {"name":"Gussy","gain":28},
    {"name":"Lucho","gain":31},
    {"name":"Diannne","gain":-50},
    {"name":"Tommie","gain":-32},
    {"name":"Marilin","gain":3},
    {"name":"Thaddeus","gain":30},
    {"name":"Herrick","gain":-34},
    {"name":"Analise","gain":2},
    {"name":"Kris","gain":36},
    {"name":"Inness","gain":-24},
    {"name":"Gilbertina","gain":-17},
    {"name":"Berthe","gain":-35},
    {"name":"Blayne","gain":3},
    {"name":"Maryjo","gain":-20},
    {"name":"Blake","gain":21},
    {"name":"Hilary","gain":-18},
    {"name":"Mathew","gain":-5},
    {"name":"Hally","gain":49},
    {"name":"Belinda","gain":3},
    {"name":"Basilio","gain":36},
    {"name":"Ansel","gain":-48},
    {"name":"Zora","gain":-3},
    {"name":"Jeffie","gain":49},
    {"name":"Pippy","gain":4},
    {"name":"Gillan","gain":5},
    {"name":"Matthus","gain":37},
    {"name":"Brendan","gain":-14},
    {"name":"Althea","gain":-26},
    {"name":"Gretel","gain":-6},
    {"name":"Scottie","gain":30},
    {"name":"Michail","gain":47},
    {"name":"Gabie","gain":-45},
    {"name":"Donia","gain":-34},
    {"name":"Benjie","gain":-14},
    {"name":"Holmes","gain":-26},
    {"name":"Toddie","gain":-14},
    {"name":"Michel","gain":24},
    {"name":"Danna","gain":30},
    {"name":"Cookie","gain":-35},
    {"name":"Kylen","gain":-23},
    {"name":"Fairlie","gain":27},
    {"name":"Kaine","gain":45},
    {"name":"Rock","gain":-42},
    {"name":"Aubree","gain":-6},
    {"name":"Alyss","gain":35},
    {"name":"Dyanna","gain":-47},
    {"name":"Ingrim","gain":35},
    {"name":"Allyson","gain":-41},
    {"name":"Arte","gain":-15},
    {"name":"Godard","gain":-36},
    {"name":"Elfrida","gain":31},
    {"name":"Jourdan","gain":47},
    {"name":"Wynn","gain":-3},
    {"name":"Andreas","gain":-31},
    {"name":"Erwin","gain":32},
    {"name":"Cozmo","gain":-49},
    {"name":"Diandra","gain":-29},
    {"name":"Othilie","gain":-6},
    {"name":"Janean","gain":-37},
    {"name":"Josepha","gain":22}]
    res.send(dummyData)
  },

  getGlobalBoard: (req, res) => {
    //console.log('metadata req', req.body)
    var dummyData = [{"name":"Theodoric","gain":24},
    {"name":"Cchaddie","gain":21},
    {"name":"Emelen","gain":26},
    {"name":"Torin","gain":-40},
    {"name":"Sibilla","gain":-23},
    {"name":"Cher","gain":45},
    {"name":"Joanne","gain":7},
    {"name":"Margo","gain":-18},
    {"name":"Kelli","gain":-36},
    {"name":"Hortensia","gain":-19},
    {"name":"Gino","gain":1},
    {"name":"Reg","gain":-45},
    {"name":"Jori","gain":22},
    {"name":"Ali","gain":21},
    {"name":"Kelly","gain":-17},
    {"name":"Lalo","gain":-42},
    {"name":"Somerset","gain":-38},
    {"name":"Inge","gain":-2},
    {"name":"Sullivan","gain":-18},
    {"name":"Gonzalo","gain":48},
    {"name":"Nevins","gain":-15},
    {"name":"Bevon","gain":45},
    {"name":"Jeri","gain":39},
    {"name":"Clive","gain":-36},
    {"name":"Zilvia","gain":-3},
    {"name":"Abbey","gain":-7},
    {"name":"Baudoin","gain":13},
    {"name":"Gasparo","gain":-49},
    {"name":"Celie","gain":-5},
    {"name":"Bern","gain":17},
    {"name":"Courtney","gain":-6},
    {"name":"Goober","gain":24},
    {"name":"Paulie","gain":10},
    {"name":"Ginger","gain":-18},
    {"name":"Farris","gain":40},
    {"name":"Lavina","gain":24},
    {"name":"Lucila","gain":10},
    {"name":"Elinor","gain":-5},
    {"name":"Sigismund","gain":12},
    {"name":"Anderea","gain":31},
    {"name":"Felipe","gain":-42},
    {"name":"Stace","gain":-35},
    {"name":"Mellicent","gain":33},
    {"name":"Dot","gain":5},
    {"name":"Irv","gain":-11},
    {"name":"Nicolette","gain":-43},
    {"name":"Lindie","gain":32},
    {"name":"Bette-ann","gain":-12},
    {"name":"Abba","gain":-12},
    {"name":"Stanford","gain":40},
    {"name":"Jenilee","gain":49},
    {"name":"Foster","gain":12},
    {"name":"Andee","gain":27},
    {"name":"Pernell","gain":41},
    {"name":"Celine","gain":17},
    {"name":"Chase","gain":-3},
    {"name":"Emilee","gain":48},
    {"name":"Clareta","gain":35},
    {"name":"Elisa","gain":30},
    {"name":"Graeme","gain":44},
    {"name":"Astra","gain":-9},
    {"name":"Giralda","gain":-20},
    {"name":"Thom","gain":26},
    {"name":"Natalina","gain":-22},
    {"name":"Lind","gain":7},
    {"name":"Ruy","gain":42},
    {"name":"Thurston","gain":16},
    {"name":"Hobie","gain":26},
    {"name":"Hyacinthe","gain":-11},
    {"name":"Willard","gain":2},
    {"name":"Brunhilde","gain":-48},
    {"name":"Olivero","gain":13},
    {"name":"Maison","gain":33},
    {"name":"Donal","gain":-48}]
    res.send(dummyData)
  },

  //auto update
  // const updateRule = new schedule.RecurrenceRule();
  // updateRule.hour = 9;
  // updateRule.minute = 0;

  // const updateJob = schedule.scheduleJob(updateRule, async () => {
  //   try {
  //     // 在此處進行自動更新的 POST 請求
  //     const response = await axios.post('your_api_url', { your_data });
  //     console.log('Auto update success:', response.data);
  //   } catch (error) {
  //     console.error('Auto update error:', error);
  //   }
  // });

}